"""Fixed race categories

Revision ID: 1b3817565d89
Revises: 48c397bb565d
Create Date: 2025-11-07 21:06:11.153142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3817565d89'
down_revision = '48c397bb565d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_racecategories',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('race_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_category_id'], ['race_category.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'race_category_id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('race_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_category_id'], ['race_category.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'team_id', name='uq_race_team')
    )
    op.drop_table('race_teams')
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_checkpoint_team_race', ['checkpoint_id', 'team_id', 'race_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_checkpoint_team_race', type_='unique')

    op.create_table('race_teams',
    sa.Column('race_id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'team_id')
    )
    op.drop_table('registration')
    op.drop_table('race_racecategories')
    op.drop_table('race_category')
    # ### end Alembic commands ###
