"""Add support for adding Images checkpoint logs.

Revision ID: 48c397bb565d
Revises: cbd5daf19086
Create Date: 2025-08-07 21:49:44.455028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c397bb565d'
down_revision = 'cbd5daf19086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_checkpoint_log_image_id",  # <-- add a name here
            'image',
            ['image_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_id')

    op.drop_table('image')
    # ### end Alembic commands ###
