"""add disqualified flag to registration

Revision ID: 67c6913a8bca
Revises: add_user_position
Create Date: 2026-01-25 14:54:11.554485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c6913a8bca'
down_revision = 'add_user_position'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disqualified', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('disqualified')

    # ### end Alembic commands ###
