"""Added race time constraints

Revision ID: 867f8a3b3276
Revises: 1b3817565d89
Create Date: 2025-11-08 21:17:45.840274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867f8a3b3276'
down_revision = '1b3817565d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_showing_checkpoints_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_showing_checkpoints_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('start_logging_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_logging_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('end_logging_at')
        batch_op.drop_column('start_logging_at')
        batch_op.drop_column('end_showing_checkpoints_at')
        batch_op.drop_column('start_showing_checkpoints_at')

    # ### end Alembic commands ###
