"""Added race time constraints

Revision ID: 867f8a3b3276
Revises: 1b3817565d89
Create Date: 2025-11-08 21:17:45.840274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867f8a3b3276'
down_revision = '1b3817565d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        # add as nullable first to avoid failing on existing rows
        batch_op.add_column(sa.Column('start_showing_checkpoints_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_showing_checkpoints_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_logging_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_logging_at', sa.DateTime(), nullable=True))

    # backfill existing races with a safe default (now) to satisfy NOT NULL
    op.execute(sa.text(
        """
        UPDATE race
        SET
            start_showing_checkpoints_at = COALESCE(start_showing_checkpoints_at, NOW()),
            end_showing_checkpoints_at   = COALESCE(end_showing_checkpoints_at,   NOW()),
            start_logging_at             = COALESCE(start_logging_at,             NOW()),
            end_logging_at               = COALESCE(end_logging_at,               NOW())
        """
    ))

    # enforce NOT NULL after data is present
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('start_showing_checkpoints_at', nullable=False)
        batch_op.alter_column('end_showing_checkpoints_at', nullable=False)
        batch_op.alter_column('start_logging_at', nullable=False)
        batch_op.alter_column('end_logging_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('end_logging_at')
        batch_op.drop_column('start_logging_at')
        batch_op.drop_column('end_showing_checkpoints_at')
        batch_op.drop_column('start_showing_checkpoints_at')

    # ### end Alembic commands ###
