"""add email_sent flag to registration

Revision ID: 910f292d2d08
Revises: 0be8af6a4d52
Create Date: 2025-12-30 14:40:42.519617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910f292d2d08'
down_revision = '0be8af6a4d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
