"""add image distance to checkpoint log

Revision ID: add_image_distance
Revises: add_image_position
Create Date: 2026-01-11 10:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_image_distance'
down_revision = 'add_image_position'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_distance_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.drop_column('image_distance_km')

    # ### end Alembic commands ###
