"""add image position to checkpoint log

Revision ID: add_image_position
Revises: 910f292d2d08
Create Date: 2026-01-11 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_image_position'
down_revision = '910f292d2d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.drop_column('image_longitude')
        batch_op.drop_column('image_latitude')

    # ### end Alembic commands ###
