"""add user position to checkpoint log

Revision ID: add_user_position
Revises: add_image_distance
Create Date: 2026-01-11 10:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_position'
down_revision = 'add_image_distance'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('user_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('user_distance_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkpoint_log', schema=None) as batch_op:
        batch_op.drop_column('user_distance_km')
        batch_op.drop_column('user_longitude')
        batch_op.drop_column('user_latitude')

    # ### end Alembic commands ###
