"""Added admin support

Revision ID: cbd5daf19086
Revises: ea22dcf7cbee
Create Date: 2024-12-30 11:42:59.579814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd5daf19086'
down_revision = 'ea22dcf7cbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_administrator', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_administrator')

    # ### end Alembic commands ###
